### ISSUE TITLE
Cannot generate postalcode from state with "nl" locale, "Secondary key not found"

### ISSUE THREAD

**Issue by MrDienns** [serpro69/kotlin-faker#126]
Hello,

Discovered an issue with postcode generation using state. Not sure if it's related to #125, but the below code gives the below error;

```kotlin
val faker = faker {
    fakerConfig {
        locale = "nl"
    }
}

println(faker.address.postcodeByState(faker.address.state()))
```

Results in;
```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:772) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:753) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:309) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.6.3.jar!/:2.6.3]
        at nl.fruitsinc.test.faker.FakerApplicationKt.main(FakerApplication.kt:89) ~[classes!/:0.1.0-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[faker-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[faker-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[faker-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[faker-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
Caused by: java.util.NoSuchElementException: Secondary key 'Zeeland' not found.
        at io.github.serpro69.kfaker.FakerService.getRawValue-EpprjwY(FakerService.kt:232) ~[kotlin-faker-1.10.0.jar!/:1.10.0]
        at io.github.serpro69.kfaker.FakerService.resolve(FakerService.kt:292) ~[kotlin-faker-1.10.0.jar!/:1.10.0]
        at io.github.serpro69.kfaker.provider.AbstractFakeDataProvider$returnOrResolveUnique$result$2.invoke(AbstractFakeDataProvider.kt:117) ~[kotlin-faker-1.10.0.jar!/:1.10.0]
        at io.github.serpro69.kfaker.provider.AbstractFakeDataProvider$returnOrResolveUnique$result$2.invoke(AbstractFakeDataProvider.kt:117) ~[kotlin-faker-1.10.0.jar!/:1.10.0]
        at io.github.serpro69.kfaker.provider.AbstractFakeDataProvider$resolve$1.invoke(AbstractFakeDataProvider.kt:57) ~[kotlin-faker-1.10.0.jar!/:1.10.0]
        at io.github.serpro69.kfaker.provider.AbstractFakeDataProvider$resolve$1.invoke(AbstractFakeDataProvider.kt:56) ~[kotlin-faker-1.10.0.jar!/:1.10.0]
        at io.github.serpro69.kfaker.provider.AbstractFakeDataProvider.returnOrResolveUnique(AbstractFakeDataProvider.kt:117) ~[kotlin-faker-1.10.0.jar!/:1.10.0]
        at io.github.serpro69.kfaker.provider.AbstractFakeDataProvider.returnOrResolveUnique$default(AbstractFakeDataProvider.kt:108) ~[kotlin-faker-1.10.0.jar!/:1.10.0]
        at io.github.serpro69.kfaker.provider.AbstractFakeDataProvider.resolve(AbstractFakeDataProvider.kt:83) ~[kotlin-faker-1.10.0.jar!/:1.10.0]
        at io.github.serpro69.kfaker.provider.Address.postcodeByState(Address.kt:26) ~[kotlin-faker-1.10.0.jar!/:1.10.0]
        at nl.fruitsinc.test.faker.FakerApplication.fakeTestResult(FakerApplication.kt:80) ~[classes!/:0.1.0-SNAPSHOT]
        at nl.fruitsinc.test.faker.FakerApplication.run(FakerApplication.kt:38) ~[classes!/:0.1.0-SNAPSHOT]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:769) ~[spring-boot-2.6.3.jar!/:2.6.3]
        ... 13 common frames omitted
```

I tried to lowercase the resulted state, but doesn't seem to change the outcome

**Comment by serpro69** [comment]
So as mentioned above, the `nl.yml` file does not contain `address.postcode_by_state` key, therefore the parameter that the function `postcodeByState` expects and the value it returns are based on the default `en` locale coming from `en/address.yml` file:  https://github.com/serpro69/kotlin-faker/blob/8a1abbba1ab30692a2147147ee31fd1194315e59/core/src/main/resources/locales/en/address.yml#L513

So this issue is not valid due to incomplete dict localization for `nl` locale.

I don't think I'll be able to fix the yml file myself as it requires at least some "domain" knowledge for the given locale. And although I prefer not to make direct changes to the yml files in kotlin-faker source code as it makes it harder to merge changes from upstream, if you're willing to update the `nl.yml` file to include the missing data - I'll consider merging it in kotlin-faker directly.

For now I'll close this issue as invalid.
