### ISSUE TITLE
1.7.2-SNAPSHOT failing when spring-boot-starter-test not included in project dependencies

### ISSUE THREAD

**Issue by johanvergeer** [serpro69/kotlin-faker#85]
I'm running into something weird here, and I can't figure out what the underlying issue is, so here it goes. 

I created a brand new project (Gradle Kotlin DSL) and created a very simple test that uses `kotlin-faker`. 

__build.gradle.kts__ (without `spring-boot-starter-test` dependency)

```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.5.0"
    application
}

group = "me.jve"

repositories {
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }
    mavenCentral()
}


val kotestVersion = "4.4.3"
val kotlinFakerVersion = "1.7.2-SNAPSHOT"

dependencies {
    testImplementation(kotlin("test-junit5"))
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.6.0")
    testImplementation("io.kotest:kotest-runner-junit5:$kotestVersion")
    testImplementation("io.kotest:kotest-property:$kotestVersion")
    testImplementation("io.github.serpro69:kotlin-faker:$kotlinFakerVersion")
}

tasks.test {
    useJUnitPlatform()
}

tasks.withType<KotlinCompile>() {
    kotlinOptions.jvmTarget = "11"
}
```

__FakerTest.kt__

```kotlin
import io.github.serpro69.kfaker.Faker
import io.kotest.core.spec.style.BehaviorSpec
import io.kotest.matchers.shouldBe

class FakerTest: BehaviorSpec() {
    private val faker = Faker()

    init {
        Given("nothing") {
            When("running a test using Faker") {
                Then("It won't run") {
                    1 + 1 shouldBe 2
                }
            }
        }
    }
}
```

This will give the following error:

```
io.kotest.core.SpecInstantiationException: Could not create instance of class FakerTest
	at io.kotest.engine.spec.InstantiateSpecKt.javaReflectNewInstance(instantiateSpec.kt:37)
	at io.kotest.engine.spec.InstantiateSpecKt.createAndInitializeSpec(instantiateSpec.kt:22)
	at io.kotest.engine.spec.SpecExecutor.createInstance(SpecExecutor.kt:53)
	at io.kotest.engine.spec.SpecExecutor.execute(SpecExecutor.kt:40)
	at io.kotest.engine.launchers.DefaultSpecLauncher$sequential$$inlined$forEach$lambda$1$1.invokeSuspend(DefaultSpecLauncher.kt:56)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Constructor.call(CallerImpl.kt:41)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at io.kotest.engine.spec.InstantiateSpecKt.javaReflectNewInstance(instantiateSpec.kt:35)
	... 9 more
Caused by: java.lang.NoClassDefFoundError: org/yaml/snakeyaml/error/YAMLException
	at faker.com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:465)
	at faker.com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:368)
	at faker.com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15)
	at faker.com.fasterxml.jackson.databind.ObjectReader.createParser(ObjectReader.java:1048)
	at faker.com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1426)
	at io.github.serpro69.kfaker.Mapper.readValue(Mapper.kt:15)
	at io.github.serpro69.kfaker.FakerService.readCategory(FakerService.kt:167)
	at io.github.serpro69.kfaker.FakerService.load(FakerService.kt:65)
	at io.github.serpro69.kfaker.FakerService.<init>(FakerService.kt:32)
	at io.github.serpro69.kfaker.Faker.<init>(Faker.kt:14)
	at io.github.serpro69.kfaker.Faker.<init>(Faker.kt:13)
	at FakerTest.<init>(FakerTest.kt:6)
	... 16 more
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.error.YAMLException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 28 more
```

## Temporary solution

I have to add `testImplementation("org.springframework.boot:spring-boot-starter-test:2.4.5")` to the project dependencies in order to run the tests. 

## Older Faker version

The previous version of `kotlin-faker` (1.7.1) doesn't have this issue.

**Comment by serpro69** [comment]
Hi @johanvergeer ,

I think it could be same as #79.
Could you try the latest rc / snapshot versions?

**Comment by johanvergeer** [comment]
Yes, `1.8.0-rc.0` works.

The latest `1.7.2-SNAPSHOT` still has the same issue.

**Comment by serpro69** [comment]
Thanks for confirming.
The `1.7.2-SNAPSHOT` should not have been there in the first place - I was incorrectly calculating the next snapshot version with the gradle plugin. Don't really see the point in fixing it either, since it's a snapshot. 
You can also try `1.8.0-SNAPSHOT` if you want to use latest snapshots instead of released versions or rc, that should also work fine.
